require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IndicatorSetsController do

  # This should return the minimal set of attributes required to create a valid
  # IndicatorSet. As you add validations to IndicatorSet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IndicatorSetsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all indicator_sets as @indicator_sets" do
      indicator_set = IndicatorSet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:indicator_sets).should eq([indicator_set])
    end
  end

  describe "GET show" do
    it "assigns the requested indicator_set as @indicator_set" do
      indicator_set = IndicatorSet.create! valid_attributes
      get :show, {:id => indicator_set.to_param}, valid_session
      assigns(:indicator_set).should eq(indicator_set)
    end
  end

  describe "GET new" do
    it "assigns a new indicator_set as @indicator_set" do
      get :new, {}, valid_session
      assigns(:indicator_set).should be_a_new(IndicatorSet)
    end
  end

  describe "GET edit" do
    it "assigns the requested indicator_set as @indicator_set" do
      indicator_set = IndicatorSet.create! valid_attributes
      get :edit, {:id => indicator_set.to_param}, valid_session
      assigns(:indicator_set).should eq(indicator_set)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IndicatorSet" do
        expect {
          post :create, {:indicator_set => valid_attributes}, valid_session
        }.to change(IndicatorSet, :count).by(1)
      end

      it "assigns a newly created indicator_set as @indicator_set" do
        post :create, {:indicator_set => valid_attributes}, valid_session
        assigns(:indicator_set).should be_a(IndicatorSet)
        assigns(:indicator_set).should be_persisted
      end

      it "redirects to the created indicator_set" do
        post :create, {:indicator_set => valid_attributes}, valid_session
        response.should redirect_to(IndicatorSet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved indicator_set as @indicator_set" do
        # Trigger the behavior that occurs when invalid params are submitted
        IndicatorSet.any_instance.stub(:save).and_return(false)
        post :create, {:indicator_set => { "name" => "invalid value" }}, valid_session
        assigns(:indicator_set).should be_a_new(IndicatorSet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IndicatorSet.any_instance.stub(:save).and_return(false)
        post :create, {:indicator_set => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested indicator_set" do
        indicator_set = IndicatorSet.create! valid_attributes
        # Assuming there are no other indicator_sets in the database, this
        # specifies that the IndicatorSet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IndicatorSet.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => indicator_set.to_param, :indicator_set => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested indicator_set as @indicator_set" do
        indicator_set = IndicatorSet.create! valid_attributes
        put :update, {:id => indicator_set.to_param, :indicator_set => valid_attributes}, valid_session
        assigns(:indicator_set).should eq(indicator_set)
      end

      it "redirects to the indicator_set" do
        indicator_set = IndicatorSet.create! valid_attributes
        put :update, {:id => indicator_set.to_param, :indicator_set => valid_attributes}, valid_session
        response.should redirect_to(indicator_set)
      end
    end

    describe "with invalid params" do
      it "assigns the indicator_set as @indicator_set" do
        indicator_set = IndicatorSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IndicatorSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => indicator_set.to_param, :indicator_set => { "name" => "invalid value" }}, valid_session
        assigns(:indicator_set).should eq(indicator_set)
      end

      it "re-renders the 'edit' template" do
        indicator_set = IndicatorSet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IndicatorSet.any_instance.stub(:save).and_return(false)
        put :update, {:id => indicator_set.to_param, :indicator_set => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested indicator_set" do
      indicator_set = IndicatorSet.create! valid_attributes
      expect {
        delete :destroy, {:id => indicator_set.to_param}, valid_session
      }.to change(IndicatorSet, :count).by(-1)
    end

    it "redirects to the indicator_sets list" do
      indicator_set = IndicatorSet.create! valid_attributes
      delete :destroy, {:id => indicator_set.to_param}, valid_session
      response.should redirect_to(indicator_sets_url)
    end
  end

end
